export const BACKEND_URL = 'http://localhost:3001';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_PASSWORD_CHANGE_REQUEST = 'USER_PASSWORD_CHANGE_REQUEST';
export const USER_PASSWORD_CHANGE_SUCCESS = 'USER_PASSWORD_CHANGE_SUCCESS';
export const USER_PASSWORD_CHANGE_FAILURE = 'USER_PASSWORD_CHANGE_FAILURE';
export const USER_PASSWORD_CHANGE_CLEAR = 'USER_PASSWORD_CHANGE_CLEAR';

export const USER_PASSWORD_RESET_REQUEST = 'USER_PASSWORD_RESET_REQUEST';
export const USER_PASSWORD_RESET_SUCCESS = 'USER_PASSWORD_RESET_SUCCESS';
export const USER_PASSWORD_RESET_FAILURE = 'USER_PASSWORD_RESET_FAILURE';
export const USER_PASSWORD_RESET_CLEAR = 'USER_PASSWORD_CHANGE_CLEAR';

export const FETCH_REPORTS_REQUEST = 'FETCH_REPORTS_REQUEST';
export const FETCH_REPORTS_SUCCESS = 'FETCH_REPORTS_SUCCESS';
export const FETCH_REPORTS_FAILURE = 'FETCH_REPORTS_FAILURE';
export const CLEAR_REPORTS_STATE = 'CLEAR_REPORTS_STATE';

export const FETCH_COMPANY_REQUEST = 'FETCH_COMPANY_REQUEST';
export const FETCH_COMPANY_SUCCESS = 'FETCH_COMPANY_SUCCESS';
export const FETCH_COMPANY_FAILURE = 'FETCH_COMPANY_FAILURE';
export const CLEAR_COMPANY_STATE = 'CLEAR_COMPANY_STATE';

export const FETCH_COMPANY_USER_REQUEST = 'FETCH_COMPANY_USER_REQUEST';
export const FETCH_COMPANY_USER_SUCCESS = 'FETCH_COMPANY_USER_SUCCESS';
export const FETCH_COMPANY_USER_FAILURE = 'FETCH_COMPANY_USER_FAILURE';
export const CLEAR_COMPANY_USER_STATE = 'CLEAR_COMPANY_USER_STATE';


